version: "3.7"

services:
  sonarqube:
    image: sonarqube:8.2-community
    container_name: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=${POSTGRES_USER}
      - SONARQUBE_JDBC_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    networks:
      - traefik
      - net
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarqube"
      - "traefik.sonar.frontend.rule=Host:${EXTERNAL_URL}"
      - "traefik.sonar.port=9000"
      - "docker.group=sonarqube"

  db:
    image: postgres
    container_name: sonarqube-db
    restart: always
    networks:
      - net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql/data:Z
    labels:
      - "docker.group=sonarqube"

networks:
  net:
  traefik:
    external:
      name: traefik

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
